{
 "title": "Choupettor",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "sum Mona detected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "changes(monaeating[$__interval]) / 2 ",
     "legendFormat": "Count by select range"
    }
   ]
  },
  {
   "title": "Mona food lifecycle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "detectionstarting", "legendFormat": "Detection starting" },
    { "expr": "monaeating", "legendFormat": "Mona is eating" }
   ]
  },
  {
   "title": "Cat food v2 state",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "scrip_state{scrip_state=\"running\"}",
     "legendFormat": "running"
    }
   ]
  },
  {
   "title": "sum detection started",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "changes(detectionstarting[$__interval]) / 2 ",
     "legendFormat": "Count by select range"
    }
   ]
  },
  {
   "title": "sum Mona detected",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "count_monaeating", "legendFormat": "sum per day" }
   ]
  },
  {
   "title": "Mona spend times to eat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "amount_monaeating_in_seconds", "legendFormat": "amount times per day" }
   ]
  }
 ]
}