---
- hosts: raspberrypi-mona
  roles:
    - grafana
  vars:
    grafana_security:
      admin_user: admin
      admin_password: the password :P
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://prometheus:9090'
        basicAuth: false
