---
- hosts: raspberrypi-mona
  roles:
    - copy-files
    - grafana
  vars:
    grafana_security:
      admin_user: admin
      admin_password: the password :P
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://prometheus:9090'
        basicAuth: false
    grafana_dashboards:
      - dashboard_id: 1860
      revision_id: 16
      datasource: prometheus
