---
- hosts: raspberrypi-mona
  roles:
  - copy-files
  - prometheus
  vars:
    prometheus_storage_retention : 1y
    prometheus_scrape_configs:
      - job_name: prometheus
        metrics_path: /metrics
        static_configs:
          - targets:
            - "raspberrypi:9090"
      - job_name: node_exporter
        metrics_path: /metrics
        static_configs:
          - targets:
            - "raspberrypi:9100"
      - job_name: python_exporter
        scrape_interval: 1s
        static_configs:
          - targets:
            - "raspberrypi:8000"

